### ISSUE TITLE
Circle radius is 2 not 4

### ISSUE THREAD

**Issue by ramiromagno** [hir0ok/w4#2]
I think you have a mistake in the code used for plotting the circle:

```
x1 = 4.0*cos(theta);
y1 = 4.0*sin(theta);
```
The `4.0` should have been instead a `2.0`.

Source file: https://github.com/hir0ok/w4/blob/f34b6785c831304833aae6e862c51818f9639521/W4demo_FujisawaProblem.ipynb

**Comment by hir0ok** [comment]
Thanks a lot!
It's fixed now.

**Comment by ramiromagno** [comment]
Thank you!
